-- AlterTable
ALTER TABLE "Fundraiser" ADD COLUMN     "category" TEXT NOT NULL DEFAULT 'General',
ADD COLUMN     "goal" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "organizer" TEXT NOT NULL DEFAULT 'Anonymous',
ADD COLUMN     "raised" DOUBLE PRECISION NOT NULL DEFAULT 0;
